// tools.mjs — single source of truth for MCP tool DEFINITIONS (Wave U-1).
// Both surfaces import this so the tool LIST can never re-diverge:
//   - stdio  (server.mjs)        → TOOLS.filter(forStdio)  + dynamic agent_<name>
//   - remote (hub.mjs /mcp, SSE) → TOOLS.filter(forRemote) + dynamic agent_<name>
//
// `surfaces` tags where a tool is NOT on both surfaces yet:
//   ['stdio']  = local-index / a2a act tools the hub can't serve yet (Wave U-2 work).
//   ['remote'] = hub-in-process only (browser checkpoint, workflow store) — no /api proxy on stdio.
// Untagged = both surfaces.
//
// PROXY = the dispatch knowledge for pure /api-proxy tools, shared so the route is the only truth:
//   server.mjs already proxies stdio→hub('/api/…'); hub.mjs loops back to its own /api for the same tools.

export const TOOLS = [
  { name: 'search_agents', surfaces: ['stdio'], description: 'Search the agent index. Returns small refs (id/name/company/skill/tags) — token-light. Use get_agent for full detail.',
    inputSchema: { type: 'object', properties: { query: { type: 'string' }, limit: { type: 'number' } }, required: ['query'] } },
  { name: 'get_agent', surfaces: ['stdio'], description: 'Get one agent\'s full card by id (on demand).',
    inputSchema: { type: 'object', properties: { id: { type: 'string' } }, required: ['id'] } },
  { name: 'search_workflows', surfaces: ['stdio'], description: 'Search the workflow/automation index. Returns small refs. Use get_workflow for the full definition.',
    inputSchema: { type: 'object', properties: { query: { type: 'string' }, limit: { type: 'number' } }, required: ['query'] } },
  { name: 'get_workflow', surfaces: ['stdio'], description: 'Get one workflow\'s full definition (steps) by id.',
    inputSchema: { type: 'object', properties: { id: { type: 'string' } }, required: ['id'] } },
  { name: 'search_automations', surfaces: ['stdio'], description: 'Search the automation index (trigger-bound workflow runs: schedule/build_state). Returns small refs — token-light. Use get_automation for the full definition.',
    inputSchema: { type: 'object', properties: { query: { type: 'string' }, limit: { type: 'number' } }, required: ['query'] } },
  { name: 'get_automation', surfaces: ['stdio'], description: 'Get one automation\'s full definition (trigger + bound workflow + default input) by id.',
    inputSchema: { type: 'object', properties: { id: { type: 'string' } }, required: ['id'] } },
  { name: 'search_integrations', surfaces: ['stdio'], description: 'Search the integration index (connected MCP servers + their external-action tools: email/post/etc). Returns small refs (id/label/kind/enabled/toolCount/tags) — token-light. Use get_integration for the full tool list.',
    inputSchema: { type: 'object', properties: { query: { type: 'string' }, limit: { type: 'number' } }, required: ['query'] } },
  { name: 'get_integration', surfaces: ['stdio'], description: 'Get one integration\'s full definition (kind + command/url + tools with accepts/emits) by id.',
    inputSchema: { type: 'object', properties: { id: { type: 'string' } }, required: ['id'] } },
  { name: 'add_integration', description: 'Register an MCP server with Shenron so its tools appear in plan_flow\'s available list and resolve as flow nodes. IMPORTANT: the tools YOUR client connects (e.g. claude.ai\'s Gmail) are invisible to Shenron — MCP servers cannot see each other — so to let a flow use such a service, register it here (or rely on agent:browser-control for UI-only services). kind defaults to "mcp" ("search" for a search-provider). Provide command (stdio) or url (HTTP) and the tools it exposes.',
    inputSchema: { type: 'object', properties: { id: { type: 'string' }, label: { type: 'string' }, kind: { type: 'string', enum: ['mcp', 'search'] }, command: { type: 'string' }, url: { type: 'string' }, tools: { type: 'array', description: '[{name, accepts?, emits?}]' } }, required: ['id', 'label'] } },
  { name: 'add_automation', description: 'Register an automation that auto-runs a saved workflow on a schedule (cron) or a build-state event. Schedule example: trigger {type:"schedule", when:"0 9 * * 1"} (every Mon 9am, 5-field cron). NOTE: the in-hub scheduler fires ONLY while the hub host is running — for phone-only / no-always-on-host it will NOT fire (use an external scheduler like Google Apps Script); check the returned `note`.',
    inputSchema: { type: 'object', properties: { name: { type: 'string' }, trigger: { type: 'object', description: '{type:"schedule",when:"<cron>"} or {type:"build_state",match:{...}}' }, workflow: { type: 'string', description: 'saved workflow id to run' }, input: { type: 'string' } }, required: ['name', 'trigger', 'workflow'] } },
  { name: 'toggle_automation', description: 'Enable or disable a saved automation (pause/resume) without deleting it — a disabled automation is skipped by the in-hub scheduler and by fire_event, effective immediately (no restart). Mirrors the cockpit toggle. Re-enable with on:true.',
    inputSchema: { type: 'object', properties: { id: { type: 'string', description: 'automation id (from search_automations)' }, on: { type: 'boolean', description: 'true = enable, false = disable/pause' } }, required: ['id', 'on'] } },
  { name: 'hub_health', description: 'Check hub liveness — returns ok:true, uptime (seconds since start), scheduler state (on/off), version. No auth required. Use to verify the hub is running before long operations, or as a watchdog ping target.',
    inputSchema: { type: 'object', properties: {} } },
  { name: 'hub_doctor', description: '神龍の初回セットアップ診断 — Node バージョン・Playwright Chromium インストール・ポート競合・A2A_SHARED_TOKEN・ユーザー登録状態を確認し、問題があれば修正コマンドを返す。詰まったらまずここを呼ぶ。',
    inputSchema: { type: 'object', properties: {} } },
  { name: 'get_config', description: 'Read 神龍\'s settings in one place (cost / scheduler / per-tier routing vendor+model / providers) + initial-setup hints (needs) + whether API keys are present. Secrets are never returned (presence only).',
    inputSchema: { type: 'object', properties: {} } },
  { name: 'set_config', description: 'Update 神龍\'s settings from natural language or structured input (takes effect immediately, no restart). e.g. {cost:"paid_ok"} / {scheduler:false} / {routing:{cheap:{vendor:"ollama",model:"llama3.2"}}}. API keys CANNOT be set here (env/.dev.vars only). Returns the full updated settings.',
    inputSchema: { type: 'object', properties: { cost: { type: 'string', enum: ['free', 'paid_ok'] }, scheduler: { type: 'boolean' }, routing: { type: 'object' }, providers: { type: 'object' } } } },
  { name: 'build_state', surfaces: ['stdio'], description: 'Summary of the Shenron state (counts, ids, attended/unattended). Summary only — not a full dump.',
    inputSchema: { type: 'object', properties: {} } },
  { name: 'plan_flow', description: '神龍: turn a natural-language goal into a flow — ordered steps, which existing tools/agents cover each (have), and which are MISSING (gaps to build). Returns `available` (registered agents/tools/workflows + built-in agent:browser-control). Saves it to the workflow store so it is viewable in the web cockpit (🗂 Flows); pass save:false to design without saving. gap controls self-extension: "ask" (default) surfaces gaps to build, "auto" auto-generates them, "off" plans with existing tools only. DISCOVER-FIRST: it researches the goal across all options (registered tools / APIs / free MCP / platforms like Apps Script / browser-control / generate) and surfaces blockers (no-API / ToS / license). If the goal is ambiguous or has blockers, it returns `clarify` (questions+options, mode:"clarify") INSTEAD of a plan — present those to the user, then call plan_flow again with their answers in `context.choices` (e.g. [{"question":"...","answer":"..."}]). Also returns summary_text + diagram_mermaid/diagram_ascii so you can show the plan and confirm before running — no web cockpit needed. ROUTING PROPOSAL (お財布適応): each step also gets a model route shown in summary_text + a `routing` array — its tier (cheap/strong, picked by the planner from the step\'s content) maps to a concrete vendor/model+cost per your wallet config: cheap→your free subscription or a local model (~$0), strong→your Claude, a high-stakes step→consensus across N models. Cheap auto-escalates to strong only if it fails. UI HINT (Wave UI S5): returns `ui_hint` ("none"|"generate") — "generate" means the flow artifact needs a custom interactive UI (form, dashboard, list-picker) beyond simple approval; when "generate", call gen_artifact_ui next. NOTE: tools your client connects (e.g. claude.ai\'s Gmail) are NOT visible here — register them with add_integration, or a UI-only service resolves to agent:browser-control. Designs, does not run — act on it with run_workflow.',
    inputSchema: { type: 'object', properties: { goal: { type: 'string' }, save: { type: 'boolean' }, gap: { type: 'string', enum: ['off', 'ask', 'auto'] }, cost: { type: 'string', enum: ['free', 'paid_ok'], description: 'free (default): only $0-marginal options, paid steps surfaced as opt-in; paid_ok: may use paid tools, cost disclosed' }, context: { type: 'object', description: 'discover-first の clarify 回答を返す時に使う: { choices: [{ question, answer }] } を入れて再呼び出しすると plan に進む' } }, required: ['goal'] } },
  { name: 'gen_component', description: '神龍: BUILD a missing tool for a gap — generates a standalone MCP server (claude/codex writes stdlib code), then spawn+handshake+run verifies it and repairs in a loop. Returns the converged code + a pending component id. The self-extension step: when no existing tool/MCP covers a step, 神龍 writes one. Approve it with approve_component to make it usable.',
    inputSchema: { type: 'object', properties: { what: { type: 'string' }, maxIters: { type: 'number' } }, required: ['what'] } },
  { name: 'gen_artifact_ui', description: '神龍: Generate a React JSX artifact UI for a flow step. The generated component runs in a sandboxed iframe (window.shenron.approve/decline/advance() for flow actions, fetch proxied via hub). Use when a flow step needs human interaction beyond a simple approval — e.g. form input, selection, dashboard.',
    inputSchema: { type: 'object', properties: { what: { type: 'string', description: 'describe the UI to generate, including what data to show and what actions the user should take' } }, required: ['what'] } },
  { name: 'list_components', description: 'List generated components (the build→vet→remember store). Small refs (id/what/approved/iters); pending (approved:false) await approve_component, approved ones are live integrations. Pass id for the full code.',
    inputSchema: { type: 'object', properties: { id: { type: 'string' } } } },
  { name: 'approve_component', description: 'Human gate: approve a generated component by id → writes prototype/mcp/generated/<id>.py and registers it as an MCP integration (ladder rejoin). After this, re-plan resolves the gap to a real mcp node and run_workflow can use it.',
    inputSchema: { type: 'object', properties: { id: { type: 'string' } }, required: ['id'] } },
  { name: 'get_permissions', description: 'Get the browser-control permission ruleset (allow/ask/deny). Read-only browser tools default allow; mutating/outbound default ask. Controls when the computer-use worker pauses for a human checkpoint.',
    inputSchema: { type: 'object', properties: {} } },
  { name: 'set_permission', description: '「常に許可」: append an allow rule to the browser-control ruleset so a tool (optionally scoped to a domain) stops asking. Mirrors the cockpit always-allow button; audited.',
    inputSchema: { type: 'object', properties: { tool: { type: 'string' }, domain: { type: 'string' } }, required: ['tool'] } },
  { name: 'make_skill', description: '神龍 Wave 7: turn a saved workflow into a Claude Code SKILL.md (a thin wrapper that calls run_workflow). Returns the slug + path so a local agent can invoke the flow as a skill.',
    inputSchema: { type: 'object', properties: { id: { type: 'string' } }, required: ['id'] } },
  { name: 'run_handoff', surfaces: ['stdio'], description: 'ACT: send one handoff to an agent skill (A2A). confirm:true to execute; otherwise returns a dry-run plan (attended).',
    inputSchema: { type: 'object', properties: { toAgentId: { type: 'string' }, skill: { type: 'string' }, input: { type: 'string' }, confirm: { type: 'boolean' } }, required: ['toAgentId', 'skill', 'input'] } },
  { name: 'run_workflow', description: 'ACT: run a workflow end-to-end (chained A2A handoffs). confirm:true to execute; otherwise returns a dry-run plan (attended).',
    inputSchema: { type: 'object', properties: { id: { type: 'string' }, input: { type: 'string' }, confirm: { type: 'boolean' } }, required: ['id', 'input'] } },
  { name: 'list_templates', description: 'List bundled flow templates (one-click installable starter flows). Small refs: id/name/summary/requires + any unmet gap warnings. Use install_template to save one as an editable workflow.',
    inputSchema: { type: 'object', properties: {} } },
  { name: 'install_template', description: 'Install a bundled template by id → saves it as an editable workflow and returns its workflowId. Any missing required credential or not-yet-enabled integration is surfaced in `warnings` (install succeeds but the flow will gap at run time until resolved).',
    inputSchema: { type: 'object', properties: { id: { type: 'string' } }, required: ['id'] } },
  { name: 'run_automation', surfaces: ['stdio'], description: 'ACT: fire one automation now (runs its bound workflow with its default input). confirm:true to execute; otherwise dry-run. --unattended mode fires enabled automations without confirm.',
    inputSchema: { type: 'object', properties: { id: { type: 'string' }, input: { type: 'string' }, confirm: { type: 'boolean' } }, required: ['id'] } },
  { name: 'fire_event', surfaces: ['stdio'], description: 'ACT: feed a build-state event (e.g. {event:"review_completed",status:"green"}); returns the enabled automations whose build_state trigger matches, and fires them when confirm:true / --unattended. The build-state-triggered run.',
    inputSchema: { type: 'object', properties: { event: { type: 'object' }, input: { type: 'string' }, confirm: { type: 'boolean' } }, required: ['event'] } },
  { name: 'send_handoff', description: 'Durable handoff: enqueue work to an agent\'s inbox (hub). Survives the recipient being OFFLINE — delivered on its next poll. Does NOT need the recipient online (unlike run_handoff).',
    inputSchema: { type: 'object', properties: { to: { type: 'string' }, skill: { type: 'string' }, input: { type: 'string' }, from: { type: 'string' } }, required: ['to', 'skill'] } },
  { name: 'list_handoffs', description: 'List inbox handoffs (hub). Small refs (id/from/to/skill/status) — token-light. Optional agent/status/limit filter.',
    inputSchema: { type: 'object', properties: { agent: { type: 'string' }, status: { type: 'string' }, limit: { type: 'number' } } } },
  { name: 'get_handoff', description: 'Get one handoff\'s full record (input/result/error/history) by id.',
    inputSchema: { type: 'object', properties: { id: { type: 'string' } }, required: ['id'] } },
  { name: 'poll_inbox', description: 'ACT as an agent coming online: heartbeat (presence) + claim its runnable (auto/approved) handoffs from the hub.',
    inputSchema: { type: 'object', properties: { agent: { type: 'string' } }, required: ['agent'] } },
  { name: 'approve_handoff', description: 'Approve an awaiting_approval handoff — it runs on the recipient\'s next poll.',
    inputSchema: { type: 'object', properties: { id: { type: 'string' } }, required: ['id'] } },
  { name: 'decline_handoff', description: 'Decline an awaiting_approval handoff.',
    inputSchema: { type: 'object', properties: { id: { type: 'string' } }, required: ['id'] } },
  { name: 'advance_artifact', description: 'Post a result to a handoff from an artifact UI, advancing the flow. Use after the user completes an action in the artifact UI (form submit, selection, etc.).',
    inputSchema: { type: 'object', properties: { id: { type: 'string', description: 'handoff id' }, result: { type: 'string', description: 'output from the artifact UI action' } }, required: ['id', 'result'] } },
  { name: 'set_flow_ui', description: 'Attach JSX artifact UI code to a saved workflow. The UI is shown in the artifact viewer when the flow runs and lets the user operate the flow (approve/advance) via window.shenron API.',
    inputSchema: { type: 'object', properties: { id: { type: 'string', description: 'workflow id' }, code: { type: 'string', description: 'JSX code (export default function App(){...}). Pass null to remove.' } }, required: ['id', 'code'] } },
  { name: 'get_flow_ui', description: 'Get the artifact UI code attached to a workflow, or null if none.',
    inputSchema: { type: 'object', properties: { id: { type: 'string', description: 'workflow id' } }, required: ['id'] } },
  { name: 'set_policy', description: 'Set an agent\'s inbox policy: "approval" (human gate) or "auto" (run on poll, automation-like).',
    inputSchema: { type: 'object', properties: { agent: { type: 'string' }, policy: { type: 'string' } }, required: ['agent', 'policy'] } },
  { name: 'set_notify', description: 'Register a webhook endpoint to receive push notifications when a flow run completes or is cancelled. format:"slack" wraps the payload as a Slack Incoming Webhook message. Optionally pass a Bearer token. Set enabled:false to pause.',
    inputSchema: { type: 'object', properties: { id: { type: 'string' }, label: { type: 'string' }, url: { type: 'string', description: 'Webhook URL (Slack/Discord/LINE/generic)' }, format: { type: 'string', enum: ['slack', 'json'], description: 'slack=Slack Incoming Webhook payload, json=raw status JSON' }, token: { type: 'string', description: 'Optional Bearer token for Authorization header' }, enabled: { type: 'boolean' } }, required: ['url'] } },
  { name: 'set_credential', description: 'Store a named credential securely (macOS Keychain on Mac, file-based elsewhere). Stored values are never returned by get_credential or list_credentials — only presence is confirmed. Use to pre-store API keys / passwords that flows reference by name.',
    inputSchema: { type: 'object', properties: { id: { type: 'string', description: 'Credential name (e.g. "rakuten-password", "twitter-api-key")' }, value: { type: 'string', description: 'The secret value' } }, required: ['id', 'value'] } },
  { name: 'get_credential', description: 'Check whether a credential exists by id. Returns { id, present: true/false } — the value is NEVER returned (stays in the vault, never enters AI context).',
    inputSchema: { type: 'object', properties: { id: { type: 'string' } }, required: ['id'] } },
  { name: 'list_credentials', description: 'List stored credential ids (names only — values are never returned).',
    inputSchema: { type: 'object', properties: {} } },
  { name: 'delete_credential', description: 'Delete a stored credential by id.',
    inputSchema: { type: 'object', properties: { id: { type: 'string' } }, required: ['id'] } },
  { name: 'export_skill', description: 'Export a generated component (skill) as a portable JSON blob. Strip internal IDs/credentials — safe to share. Returns { what, code, iters, shenron:"1" }.',
    inputSchema: { type: 'object', properties: { id: { type: 'string', description: 'Component id from list_components' } }, required: ['id'] } },
  { name: 'import_skill', description: 'Import a skill JSON blob (from export_skill or community). Saves as a pending component — approve with approve_component to activate. Provide code+what directly or a blob object.',
    inputSchema: { type: 'object', properties: { what: { type: 'string' }, code: { type: 'string' }, blob: { type: 'object', description: 'Pass the full export_skill blob here instead of what+code' } } } },
  { name: 'list_users', description: '登録済みユーザー一覧（id/email/verified/createdAt）。パスワードは返らない。',
    inputSchema: { type: 'object', properties: {} } },
  { name: 'reset_password', description: 'パスワードリセット。email だけ渡すと hub ターミナルにリセットリンクを出力（reset-request）。token + password を渡すとリセット実行（reset）。両方公開エンドポイント（認証不要）。',
    inputSchema: { type: 'object', properties: { email: { type: 'string', description: 'reset-request: メールアドレス' }, token: { type: 'string', description: 'reset: リセットリンクのトークン' }, password: { type: 'string', description: 'reset: 新しいパスワード' } } } },
  { name: 'list_runs', description: '直近 20 件のフロー実行履歴（id/flowId/status/done/total/outputs）。',
    inputSchema: { type: 'object', properties: {} } },
  { name: 'get_run', description: 'runId でフロー実行の全フィールドを取得（outputs/skipped/routerPick を含む）。',
    inputSchema: { type: 'object', properties: { id: { type: 'string' } }, required: ['id'] } },
  { name: 'stream_run', description: '実行中フローの進捗を購読: 接続時の各ノード出力 snapshot ＋ run 完了/キャンセルまで（最大 timeout 秒）待って完了ノードと最終 status を集約で返す。長時間 push ではなくスナップショット。',
    inputSchema: { type: 'object', properties: { id: { type: 'string' }, timeout: { type: 'number', description: '待機上限秒（既定 30・上限 120）' } }, required: ['id'] } },
  { name: 'test_notify', description: '有効な通知 integration (kind:notify) 全てにテスト payload を送信し、各 URL の成否を返す。',
    inputSchema: { type: 'object', properties: {} } },
  { name: 'create_agent', description: 'エージェントを作成 → 即この MCP の tool 一覧に agent_<name> として現れ、すぐ呼べる。name は小文字[a-z0-9-]。instructions=システムプロンプト（役割・出力形式）。vendor 既定 claude（あなたのサブスク＝従量0）。',
    inputSchema: { type: 'object', properties: { name: { type: 'string' }, instructions: { type: 'string', description: 'システムプロンプト（役割・振る舞い・出力形式）' }, vendor: { type: 'string', description: 'claude（既定）/codex/gemini/ollama' }, model: { type: 'string' } }, required: ['name', 'instructions'] } },
  { name: 'run_agent', description: '作成済みエージェントを実行して結果を返す（agent_<name> tool と同じ）。',
    inputSchema: { type: 'object', properties: { name: { type: 'string' }, input: { type: 'string' } }, required: ['name', 'input'] } },
  { name: 'delete_agent', description: '作成済み local エージェントを削除（進行中の run は触らない・新規受付のみ停止）。',
    inputSchema: { type: 'object', properties: { name: { type: 'string' } }, required: ['name'] } },
  { name: 'export_agent_mcp', description: 'エージェントを hub 非依存の standalone Python MCP server として書出 → 任意の MCP client に登録できるポータブル成果物。返りの registerHint に登録方法。',
    inputSchema: { type: 'object', properties: { name: { type: 'string' } }, required: ['name'] } },
  { name: 'remember', description: '神龍に長期記憶を1件保存（セッションを跨いで以降の agent 実行に自動で前置注入される）。秘密値は入れない。',
    inputSchema: { type: 'object', properties: { text: { type: 'string' }, tags: { type: 'array' } }, required: ['text'] } },
  { name: 'recall', description: '保存済みの記憶を取得。query で keyword/tag マッチ、未指定で新しい順 topN。',
    inputSchema: { type: 'object', properties: { query: { type: 'string' }, topN: { type: 'number' } } } },
  { name: 'forget', description: '記憶を id 指定で削除（recall の id）。',
    inputSchema: { type: 'object', properties: { id: { type: 'string' } }, required: ['id'] } },
  { name: 'set_check', description: 'automation に成果検証(expect)を付与/解除。expect:{kind:"assert"|"judge", rule, maxRetry}・null/省略で解除。run 完了時に flowResult を rule と突き合わせ、外れたら check_failed 通知。⚠️ judge は run 出力(PII 含みうる)を vendor LLM に送る＝新 egress。秘匿 flow は assert を使うこと。',
    inputSchema: { type: 'object', properties: { automation: { type: 'string', description: '対象 automation id' }, expect: { type: 'object', description: '{kind:"assert"|"judge", rule, maxRetry}; null で解除' } }, required: ['automation'] } },
  { name: 'list_check_results', description: '直近の成果検証結果（runId/automationId/kind/passed/reason/at）。',
    inputSchema: { type: 'object', properties: { limit: { type: 'number' } } } },
  { name: 'repair_run', description: 'Wave R-2: 失敗 run の generated component を再生成キューに投入。収束したら approve_component 待ち（approved:false）になる。onFail:notify run にも手動で使える。',
    inputSchema: { type: 'object', properties: { runId: { type: 'string', description: '修復対象の run id' } }, required: ['runId'] } },
  { name: 'login_status', description: 'browser-control の各ドメインのログイン生存状態。lastDetected=最後にログイン要求を検出した時刻 / lastOk=最後に通過した時刻 / needsLogin。無人 run でログインが切れていないか外から確認。domain 省略で全件。値（user/pass）は持たない（検出のみ）。',
    inputSchema: { type: 'object', properties: { domain: { type: 'string', description: '対象ドメイン（省略で全件）' } } } },
  { name: 'set_goal', description: '長期ゴールを記憶（神龍に預ける）。wish=願い（例「3ヶ月でフォロワー1000」）、metric=測る指標、target=目標値、current=現在値、unit=単位、deadline=期限(ISO)。id を渡すと更新（未指定フィールドは保持）。進捗 metric は自動計測せず goal_checkin で人が入れる。',
    inputSchema: { type: 'object', properties: { id: { type: 'string' }, wish: { type: 'string' }, metric: { type: 'string' }, target: { type: 'number' }, current: { type: 'number' }, unit: { type: 'string' }, deadline: { type: 'string' }, status: { type: 'string', enum: ['active', 'reached', 'stalled'] } } } },
  { name: 'get_goal', description: 'ゴール1件を id で取得（checkins 履歴 + 進捗率 pct を含む）。',
    inputSchema: { type: 'object', properties: { id: { type: 'string' } }, required: ['id'] } },
  { name: 'list_goals', description: 'ゴール一覧（小さな ref + 進捗率 pct）。',
    inputSchema: { type: 'object', properties: {} } },
  { name: 'goal_checkin', description: 'ゴールの進捗を手動で記録（最新値が現在値になる）。value=新しい現在値、note=任意メモ。target 到達で status が reached に。',
    inputSchema: { type: 'object', properties: { id: { type: 'string' }, value: { type: 'number' }, note: { type: 'string' } }, required: ['id', 'value'] } },
  { name: 'delete_goal', description: 'ゴールを id 指定で削除。',
    inputSchema: { type: 'object', properties: { id: { type: 'string' } }, required: ['id'] } },
  { name: 'list_suggestions', description: '神龍が自分の run/audit から検出した提案一覧（kind:automate=定期化候補/fix=連続 fail 中のフロー・status:open のみ既定）。提案はユーザー操作なく自動生成（外部受信箱は読まない）。',
    inputSchema: { type: 'object', properties: { status: { type: 'string', enum: ['open', 'dismissed', 'applied', 'all'], description: '省略で open のみ' } } } },
  { name: 'dismiss_suggestion', description: '提案を非表示にする（status:dismissed）。次回 tick で再検出される同パターンは新しい提案として出直す。',
    inputSchema: { type: 'object', properties: { id: { type: 'string' } }, required: ['id'] } },
  { name: 'apply_suggestion', description: '提案を適用する（automate 提案→ add_automation 相当で定期化・fix 提案→ set_check 相当で成果検証設定）。status が applied になる。',
    inputSchema: { type: 'object', properties: { id: { type: 'string' } }, required: ['id'] } },
  // --- remote-only: hub holds the workflow store + browser-control checkpoint state; stdio has no /api proxy for these.
  { name: 'save_workflow', surfaces: ['remote'], description: 'nodes/edges でフローを保存',
    inputSchema: { type: 'object', properties: { name: { type: 'string' }, nodes: { type: 'array' }, edges: { type: 'array' } }, required: ['name', 'nodes', 'edges'] } },
  { name: 'list_workflows', surfaces: ['remote'], description: '保存済みフロー一覧',
    inputSchema: { type: 'object', properties: {} } },
  { name: 'clone_workflow', surfaces: ['remote'], description: 'フローを fork（複製）して新しい編集可能なコピーを作る。元は変えずコピーを改造し、別フローに sub-flow ノードとして再利用できる。',
    inputSchema: { type: 'object', properties: { id: { type: 'string', description: '複製元の workflow id' }, name: { type: 'string', description: '新しい名前（省略時は「元名 (copy)」）' } }, required: ['id'] } },
  { name: 'get_checkpoint', surfaces: ['remote'], description: 'browser-control の承認待ちステップ取得',
    inputSchema: { type: 'object', properties: {} } },
  { name: 'resolve_checkpoint', surfaces: ['remote'], description: 'browser ステップをモバイルから承認/拒否',
    inputSchema: { type: 'object', properties: { id: { type: 'string' }, allow: { type: 'boolean' } }, required: ['id', 'allow'] } },
];

// PROXY: pure /api-proxy tools — the route IS the only implementation. server.mjs (stdio→remote hub) and
// hub.mjs (remote→loopback to own /api) both reach the same routes. (args) → { method, path, body? }.
// GET = no body. list_handoffs/get_handoff are NOT here — they filter /api/state and are handled in-process.
const enc = encodeURIComponent;
export const PROXY = {
  hub_doctor:         () => ({ method: 'GET',  path: '/api/doctor' }),
  toggle_automation: (a) => ({ method: 'POST', path: `/api/automations/${enc(a.id)}/toggle`, body: { on: a.on } }),
  list_components:   (a) => ({ method: 'GET',  path: a.id ? `/api/shenron/components?id=${enc(a.id)}` : '/api/shenron/components' }),
  approve_component: (a) => ({ method: 'POST', path: '/api/shenron/components/approve', body: { id: a.id } }),
  get_permissions:   () => ({ method: 'GET',  path: '/api/permissions' }),
  set_permission:    (a) => ({ method: 'POST', path: '/api/permissions', body: { tool: a.tool, domain: a.domain } }),
  make_skill:        (a) => ({ method: 'POST', path: '/api/shenron/skill', body: { id: a.id } }),
  send_handoff:      (a) => ({ method: 'POST', path: '/api/handoffs', body: { to: a.to, skill: a.skill, input: a.input || '', from: a.from || 'mcp' } }),
  poll_inbox:        (a) => ({ method: 'POST', path: '/api/poll', body: { agent: a.agent } }),
  approve_handoff:   (a) => ({ method: 'POST', path: `/api/handoffs/${enc(a.id)}/approve`, body: {} }),
  decline_handoff:   (a) => ({ method: 'POST', path: `/api/handoffs/${enc(a.id)}/decline`, body: {} }),
  advance_artifact:  (a) => ({ method: 'POST', path: `/api/handoffs/${enc(a.id)}/result`, body: { result: a.result } }),
  set_flow_ui:       (a) => ({ method: 'POST', path: `/api/workflows/${enc(a.id)}/ui`, body: { code: a.code } }),
  get_flow_ui:       (a) => ({ method: 'GET',  path: `/api/workflows/${enc(a.id)}/ui` }),
  set_policy:        (a) => ({ method: 'POST', path: `/api/agents/${enc(a.agent)}/policy`, body: { policy: a.policy } }),
  set_notify:        (a) => ({ method: 'POST', path: '/api/integrations', body: { id: a.id || (a.format === 'slack' ? 'slack-notify' : 'webhook-notify'), label: a.label || 'Webhook通知', kind: 'notify', url: a.url, format: a.format || 'json', token: a.token || '', enabled: a.enabled !== false, tools: [] } }),
  set_credential:    (a) => ({ method: 'POST', path: '/api/credentials', body: { action: 'set', id: a.id, value: a.value } }),
  get_credential:    (a) => ({ method: 'POST', path: '/api/credentials', body: { action: 'get', id: a.id } }),
  list_credentials:  () => ({ method: 'POST', path: '/api/credentials', body: { action: 'list' } }),
  delete_credential: (a) => ({ method: 'POST', path: '/api/credentials', body: { action: 'delete', id: a.id } }),
  export_skill:      (a) => ({ method: 'POST', path: '/api/components/export', body: { id: a.id } }),
  import_skill:      (a) => { const b = a.blob || {}; return { method: 'POST', path: '/api/components/import', body: { what: a.what || b.what, code: a.code || b.code, iters: b.iters } }; },
  list_users:        () => ({ method: 'GET',  path: '/api/auth/users' }),
  reset_password:    (a) => a.token ? { method: 'POST', path: '/api/auth/reset', body: { token: a.token, password: a.password } } : { method: 'POST', path: '/api/auth/reset-request', body: { email: a.email } },
  list_runs:         () => ({ method: 'GET',  path: '/api/runs' }),
  get_run:           (a) => ({ method: 'GET',  path: `/api/runs/${enc(a.id)}` }),
  test_notify:       () => ({ method: 'POST', path: '/api/notify/test', body: {} }),
  login_status:      (a) => ({ method: 'GET',  path: a.domain ? `/api/login-status?domain=${enc(a.domain)}` : '/api/login-status' }),
};

// REMOTE_DENY — tools too security-sensitive to expose on the remote (claude.ai) surface.
// 方針 (user 判断 2026-06-22): claude.ai 経由では「生の秘密値・権限緩和・認証/列挙」だけを遮断する。
// モバイルの通常操作（run_*・get/list_credential(presence/名前のみ)・automation 管理・state 閲覧）は残す＝
// 「遮断しつつモバイルから操作できる」を満たす。adding a name here removes it from the remote tool list (stdio keeps it).
export const REMOTE_DENY = new Set([
  'set_credential',   // 生の秘密値が claude.ai サーバーを経由する＝堀(秘密は箱から出さない)に反する。保存はローカル stdio で。
  'set_permission',   // browser-control の allow ルールを黙って広げ承認フェンスを緩める。閲覧(get_permissions)は remote 可。
  'reset_password',   // 認証操作はローカルで（リセットリンクは hub ターミナルに出る）。
  'list_users',       // アカウント列挙を remote から不可に。
]);

export const forStdio  = (t) => !t.surfaces || t.surfaces.includes('stdio');
export const forRemote = (t) => (!t.surfaces || t.surfaces.includes('remote')) && !REMOTE_DENY.has(t.name);
