// AUTO-GENERATED by prototype/mcp/trigger/gen-trigger.mjs — DO NOT EDIT BY HAND.
// Source of truth: prototype/mcp/automations.json (schedule triggers). Re-run the generator to update.
// Adopt-GLUE seam (docs/08 G1): Trigger.dev owns the cron; BuildHUD owns "what runs".
//
// Setup: `npx trigger.dev@latest init` in a project, drop this file in your /trigger dir, then
// `npx trigger.dev@latest dev` to sync the declarative schedules. The worker must run where the
// BuildHUD agents are reachable (self-hosted / dev) — Trigger.dev Cloud cannot reach localhost agents.
import { schedules } from "@trigger.dev/sdk";
import { execFile } from "node:child_process";
import { promisify } from "node:util";

const run = promisify(execFile);
const FIRE = "/Users/you/GioGio/prototype/mcp/fire.mjs";

// one-shot fire of a BuildHUD automation through the MCP server (MCP-first); needs A2A_SHARED_TOKEN in env.
async function fireAutomation(id) {
  const { stdout } = await run("node", [FIRE, id], { env: process.env, timeout: 240000, maxBuffer: 16 * 1024 * 1024 });
  return stdout;
}

// Nightly prospect → outreach — Every night, A社 finds fresh prospects and B社 drafts personalized outreach for the standing ICP.
export const nightly_prospect_outreach = schedules.task({
  id: "buildhud-nightly-prospect-outreach",
  cron: "0 2 * * *", // UTC; wrap as { pattern, timezone } for a tz
  run: async () => {
    // fires BuildHUD automation "nightly-prospect-outreach" → bound workflow "sales-to-marketing" via the MCP server
    return fireAutomation("nightly-prospect-outreach");
  },
});
