#!/usr/bin/env node
// gen-trigger.mjs — emit Trigger.dev v3 declarative scheduled tasks from automations.json.
// "Adopt, don't build" (docs/08 G1): the cron lives in Trigger.dev; automations.json stays the
// single source of truth. Re-run after adding/editing a `schedule` automation, then sync with
// `npx trigger.dev@latest dev` (or `deploy`). Only `trigger.type === "schedule"` automations
// become cron tasks here — `build_state` ones fire via fire_event from CI, not cron.
//
//   node prototype/mcp/trigger/gen-trigger.mjs        # writes ./buildhud.schedules.ts
//
// Zero-dependency (just reads JSON + writes a .ts). The emitted file needs @trigger.dev/sdk.

import fs from 'node:fs';
import path from 'node:path';
import url from 'node:url';

const HERE = path.dirname(url.fileURLToPath(import.meta.url));        // prototype/mcp/trigger
const MCP_DIR = path.join(HERE, '..');                                // prototype/mcp
const FIRE = path.join(MCP_DIR, 'fire.mjs');                          // absolute, baked at gen time
const automations = JSON.parse(fs.readFileSync(path.join(MCP_DIR, 'automations.json'), 'utf8'));
const scheduled = automations.filter((a) => a.trigger?.type === 'schedule' && a.enabled !== false);

const ident = (id) => id.replace(/[^a-zA-Z0-9]+/g, '_').replace(/^(\d)/, '_$1');
const cronOf = (t) => (typeof t.when === 'string' ? JSON.stringify(t.when) : JSON.stringify(t.when ?? '0 2 * * *'));

const tasks = scheduled.map((a) => `
// ${a.name} — ${a.summary}
export const ${ident(a.id)} = schedules.task({
  id: ${JSON.stringify('buildhud-' + a.id)},
  cron: ${cronOf(a.trigger)}, // UTC; wrap as { pattern, timezone } for a tz
  run: async () => {
    // fires BuildHUD automation "${a.id}" → bound workflow "${a.workflow}" via the MCP server
    return fireAutomation(${JSON.stringify(a.id)});
  },
});`).join('\n');

const out = `// AUTO-GENERATED by prototype/mcp/trigger/gen-trigger.mjs — DO NOT EDIT BY HAND.
// Source of truth: prototype/mcp/automations.json (schedule triggers). Re-run the generator to update.
// Adopt-GLUE seam (docs/08 G1): Trigger.dev owns the cron; BuildHUD owns "what runs".
//
// Setup: \`npx trigger.dev@latest init\` in a project, drop this file in your /trigger dir, then
// \`npx trigger.dev@latest dev\` to sync the declarative schedules. The worker must run where the
// BuildHUD agents are reachable (self-hosted / dev) — Trigger.dev Cloud cannot reach localhost agents.
import { schedules } from "@trigger.dev/sdk";
import { execFile } from "node:child_process";
import { promisify } from "node:util";

const run = promisify(execFile);
const FIRE = ${JSON.stringify(FIRE)};

// one-shot fire of a BuildHUD automation through the MCP server (MCP-first); needs A2A_SHARED_TOKEN in env.
async function fireAutomation(id) {
  const { stdout } = await run("node", [FIRE, id], { env: process.env, timeout: 240000, maxBuffer: 16 * 1024 * 1024 });
  return stdout;
}
${tasks}
`;

const target = path.join(HERE, 'buildhud.schedules.ts');
fs.writeFileSync(target, out);
console.error(`[gen-trigger] wrote ${path.relative(process.cwd(), target)} — ${scheduled.length} scheduled task(s): ${scheduled.map((a) => a.id).join(', ') || '(none)'}`);
