#!/usr/bin/env node
// gen-trigger.mjs — emit Trigger.dev v3 declarative scheduled tasks from automations.json.
// "Adopt, don't build" (docs/08 G1): the cron lives in Trigger.dev; automations.json stays the
// single source of truth. Re-run after adding/editing a `schedule` automation, then sync with
// `npx trigger.dev@latest dev` (or `deploy`). Only `trigger.type === "schedule"` automations
// become cron tasks here — `build_state` ones fire via fire_event from CI, not cron.
//
//   node prototype/mcp/trigger/gen-trigger.mjs        # writes ./shenron.schedules.ts
//
// Zero-dependency (just reads JSON + writes a .ts). The emitted file needs @trigger.dev/sdk.

import fs from 'node:fs';
import path from 'node:path';
import url from 'node:url';

const HERE = path.dirname(url.fileURLToPath(import.meta.url));        // prototype/mcp/trigger
const MCP_DIR = path.join(HERE, '..');                                // prototype/mcp
const FIRE = path.join(MCP_DIR, 'fire.mjs');                          // baked default; the emitted resolver also tries env + repo walk-up
const automations = JSON.parse(fs.readFileSync(path.join(MCP_DIR, 'automations.json'), 'utf8'));
const scheduled = automations.filter((a) => a.trigger?.type === 'schedule' && a.enabled !== false);
if (!fs.existsSync(FIRE)) console.error(`[gen-trigger] ⚠ fire.mjs not found at ${FIRE} — generated tasks fall back to SHENRON_FIRE / SHENRON_HOME / repo walk-up on the worker host`);

const baseIdent = (id) => id.replace(/[^a-zA-Z0-9]+/g, '_').replace(/^(\d)/, '_$1');
const usedIdents = new Map();
const ident = (id) => {                                              // dedup: a-b and a.b must not collide into one export
  let name = baseIdent(id);
  for (let i = 2; usedIdents.has(name); i++) name = `${baseIdent(id)}_${i}`;
  usedIdents.set(name, id);
  return name;
};
const cronOf = (t) => (typeof t.when === 'string' ? JSON.stringify(t.when) : JSON.stringify(t.when ?? '0 2 * * *'));

const tasks = scheduled.map((a) => `
// ${a.name} — ${a.summary}
export const ${ident(a.id)} = schedules.task({
  id: ${JSON.stringify('shenron-' + a.id)},
  cron: ${cronOf(a.trigger)}, // UTC; wrap as { pattern, timezone } for a tz
  run: async () => {
    // fires Shenron automation "${a.id}" → bound workflow "${a.workflow}" via the MCP server
    return fireAutomation(${JSON.stringify(a.id)});
  },
});`).join('\n');

const out = `// AUTO-GENERATED by prototype/mcp/trigger/gen-trigger.mjs — DO NOT EDIT BY HAND.
// Source of truth: prototype/mcp/automations.json (schedule triggers). Re-run the generator to update.
// Adopt-GLUE seam (docs/08 G1): Trigger.dev owns the cron; Shenron owns "what runs".
//
// Setup: \`npx trigger.dev@latest init\` in a project, drop this file in your /trigger dir, then
// \`npx trigger.dev@latest dev\` to sync the declarative schedules. The worker must run where the
// Shenron agents are reachable (self-hosted / dev) — Trigger.dev Cloud cannot reach localhost agents.
import { schedules } from "@trigger.dev/sdk";
import { execFile } from "node:child_process";
import { existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { promisify } from "node:util";

const run = promisify(execFile);
const BAKED = ${JSON.stringify(FIRE)};  // gen-time default; resolver below also tries env + repo walk-up

// Resolve fire.mjs on THIS host — no single hard-coded path. Order: SHENRON_FIRE → SHENRON_HOME →
// gen-time baked path → walk up from this generated file for prototype/mcp/fire.mjs (self-hosted layouts
// where the Trigger.dev project lives in/under the Shenron repo). Fail LOUDLY + actionably if none exist.
function resolveFire() {
  const tried = [];
  const pick = (p) => { if (!p) return null; tried.push(p); return existsSync(p) ? p : null; };
  let hit = pick(process.env.SHENRON_FIRE)
    || pick(process.env.SHENRON_HOME && join(process.env.SHENRON_HOME, "prototype/mcp/fire.mjs"))
    || pick(BAKED);
  let dir = dirname(fileURLToPath(import.meta.url));
  for (let i = 0; !hit && i < 8; i++) { hit = pick(join(dir, "prototype/mcp/fire.mjs")); const up = dirname(dir); if (up === dir) break; dir = up; }
  if (!hit) throw new Error(\`Shenron fire.mjs not found (tried: \${tried.join(", ")}). Set SHENRON_FIRE=/abs/path/to/prototype/mcp/fire.mjs on this worker.\`);
  return hit;
}

// Fire a Shenron automation through the MCP server (MCP-first). Needs A2A_SHARED_TOKEN in the worker env.
// Resolves fire.mjs per host (above) and fails LOUDLY + actionably in the run log — never an opaque ENOENT.
async function fireAutomation(id) {
  const FIRE = resolveFire();
  try {
    const { stdout } = await run("node", [FIRE, id], { env: process.env, timeout: 240000, maxBuffer: 16 * 1024 * 1024 });
    return stdout;
  } catch (e) {
    const detail = (e.stderr || e.stdout || e.message || "").toString().trim().slice(0, 500);
    throw new Error(\`Shenron automation "\${id}" failed (fire.mjs exit \${e.code ?? "?"}): \${detail}\`);
  }
}
${tasks}
`;

const target = path.join(HERE, 'shenron.schedules.ts');
fs.writeFileSync(target, out);
console.error(`[gen-trigger] wrote ${path.relative(process.cwd(), target)} — ${scheduled.length} scheduled task(s): ${scheduled.map((a) => a.id).join(', ') || '(none)'}`);
